### ISSUE TITLE
Use mocks to fix failing tests

### ISSUE THREAD

**Issue by gregjoeval** [Azure-Samples/application-insights-react-demo#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> You should be able to reproduce assuming that something in `<App/>` is using the `withAITracking` HOC

```
import React from 'react';
import ReactDOM from 'react-dom';
import {act} from 'react-dom/test-utils';
import App from './App';

it('renders without crashing', () => {
    const div = document.createElement('div');
    act(() => {
        ReactDOM.render(<App />, div);
    });
    ReactDOM.unmountComponentAtNode(div);
});
```

### Any log messages given by the failure
>I have had a unit test commented out for a while now because the `withAITracking` HOC was throwing an exception...
```
  ● Test suite failed to run

    TypeError: Object prototype may only be an Object or null: undefined
        at setPrototypeOf (<anonymous>)

      48 | }
      49 | 
    > 50 | export default mapContextToProps(contextMap)(withRouter(withAITracking(applicationInsights.reactPlugin, AppTelemetryProvider)));
         |                                                         ^
      51 | 

```

### Expected/desired behavior
> _I notice that this repo is failing its own test for what seems to be a similar reason, this example might be able to fix that_
> ### **THE FIX**
>If you're running into this, I've figured out a work around that was not described in this example. You can mock that HOC and the ReactPlugin with Jest so that you can still use your unit tests while using this example. Here is the test for my app: 

```
import React from 'react';
import ReactDOM from 'react-dom';
import {act} from 'react-dom/test-utils';
import App from './App';

jest.mock('@microsoft/applicationinsights-react-js', () => ({
    withAITracking: (reactPlugin, Component) => (<Component/>),
    ReactPlugin: Object
}));

it('renders without crashing', () => {
    const div = document.createElement('div');
    act(() => {
        ReactDOM.render(<App />, div);
    });
    ReactDOM.unmountComponentAtNode(div);
});
```
>Maybe this was pretty intuitive to someone who is better at using jest, but this wasn't an answer I stumbled upon so I figured the best way to help whoever comes next would be to create an issue with my workaround

### OS and Version?
> Windows 10

### Versions
> "@microsoft/applicationinsights-react-js": "^2.2.2",
    "@microsoft/applicationinsights-web": "^2.2.2",

**Comment by gregjoeval** [comment]
I submitted a PR to fix this and it was pulled into master so I'll close this issue

**Comment by phillijw** [comment]
I believe a common way to fix this sort of problem is to export your component in two different ways:

- Using the default, with the `withAITracking` wrapping the component
- Using a named value without `withAITracking` wrapping the component

Then in your test you pull in the named value rather than the default
